CREATE TABLE Task(
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    Title TEXT NOT NULL,
    Note TEXT,
    Starred BOOLEAN NOT NULL,
    Config INTEGER NOT NULL,
    Complete BOOLEAN NOT NULL
);

CREATE TABLE Schedule(
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    Task_ID INTEGER NOT NULL,
    Config INTEGER NOT NULL,
    Date DATE NOT NULL,
    FOREIGN KEY(Task_ID) REFERENCES Task(ID)
);

CREATE TABLE Location(
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    Title TEXT NOT NULL,
    Note TEXT,
    Config INTEGER NOT NULL
);

CREATE TABLE Task_Location(
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    Task_ID INTEGER NOT NULL,
    Location_ID INTEGER NOT NULL,
    FOREIGN KEY(Task_ID) REFERENCES Task(ID),
    FOREIGN KEY(Location_ID) REFERENCES Location(ID)
);

CREATE TABLE GPSCoordinate(
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    Location_ID INTEGER NOT NULL,
    Longitude REAL NOT NULL,
    Latitude REAL NOT NULL,
    Range REAL NOT NULL,
    FOREIGN KEY(Location_ID) REFERENCES Location(ID)
);

CREATE TABLE WiFiPosition(
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    Location_ID INTEGER NOT NULL,
    SSID TEXT NOT NULL,
    BSSID TEXT,
    MaxSignal INTEGER NOT NULL,
    MinSignal INTEGER NOT NULL,
    FOREIGN KEY(Location_ID) REFERENCES Location(ID)
);